server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://test-pichincha.ccrj6dbsodsi.us-east-1.rds.amazonaws.com:3306/test_pichincha
    username: admin
    password: QmFuY28gUGljaGluY2hhIFRlc3QgR2xvYmFudA==
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org:
      hibernate:
        SQL: debug

